### ISSUE TITLE
Weird 'Deprecated' warning appearing when setting up plugin

### ISSUE THREAD

**Issue by shreyas-a-s** [lewis6991/spaceless.nvim#11]
Hi, Lewis. First of all, the plugin is flawless as far as my usage goes. Thank you for creating it.

Secondly, this thing is not an actual 'issue' per se because it doesn't affect the functionality. I am just asking out of curiosity.

This is how I setup the plugin and as you can see, lua_ls shows a warning:

![image](https://github.com/lewis6991/spaceless.nvim/assets/137637016/71305abb-34e9-4290-847f-d6cd26143559)

When I looked into the actual plugin files, I found the line in picture below is what causing this warning because if I delete this line, save the file and go back to my plugin setup file, the warning goes away.

![image](https://github.com/lewis6991/spaceless.nvim/assets/137637016/d5259693-0b5d-4034-a967-59d00ccdabbc)

I would just like to know why this behaviour occurs and especially whether this is an intended behaviour or not.

Thanks again for the plugin as well as for reading through this message. ❤️

**Comment by lewis6991** [comment]
`setup()` isn't required, I've updated the README.

**Comment by shreyas-a-s** [comment]
I think it would be nice to include a section in README saying setup() is not required. I can make the change and do a pull request if you would like it.

**Comment by lewis6991** [comment]
No thank you. `setup()` isn't even documented and the only reference to it is in the code itself:

```lua
---@deprecated
function M.setup()
  -- moved to plugin/
end
```

In general, you can usually figure a lot out by just looking at the code. This entire plugin is only ~100LOC.

**Comment by shreyas-a-s** [comment]
Yeah, I do agree.
